version: '3'
services:
  rethinkdb:
    image: rethinkdb:2.4
    restart: always
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    volumes:
      - "rethinkdb_data:/data"
volumes:
  rethinkdb_data: